### ISSUE TITLE
OpAmp Fehler

### ISSUE THREAD

**Issue by dt-flo** [latex4ei/Schaltungstechnik-1-2#13]
In der Formelsammlung für Schaltungsthechnik findet man eine Zeichnung des idealen Operationsverstärkers, auf der zu erkennen ist, dass die Spannung u_d von Minus nach Plus geht. Im Skript von Dr. Joham ist es aber andersherum. Bitte prüft das und korrigiert diesen möglichen Fehler.

**Comment by hofbi** [comment]
Könntest du noch ein foto von der entsprechenden seite im skrip hochladen?

**Comment by dt-flo** [comment]
[opamp-skript.pdf](https://github.com/latex4ei/Schaltungstechnik-1-2/files/4792634/opamp-skript.pdf)

**Comment by dt-flo** [comment]
Wie siehts aus? Wird noch was benötigt?

**Comment by hofbi** [comment]
Ne passt. Ich werde das verbessern

**Comment by hofbi** [comment]
@emareg Wie habt ihr den hier die grafiken bearbeitet? Kannst du bei dem opamp.pdf plus und minus kurz vertauschauen
